Bug #2058 Исправить ошибку импорта в миграции.
После появления нового урлайзера, миграция, которая использовала старый, стала падать:
UnknownMigration: Migration 'custom_comments:0002_sanitize_comment_field' probably doesn't exist.
Traceback (most recent call last):
  File "/Users/Valera/www/exmo/venv/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/Users/Valera/www/exmo/exmo/exmo/custom_comments/migrations/0002_sanitize_comment_field.py", line 24, in <module>
    from core.utils import urlize, clean_message
ImportError: cannot import name urlize